apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: demo-guestbook-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: redis-service
      app: demo-guestbook-app
  template:
    metadata:
        name: redis-service
        labels:
          name: redis-service
          app: demo-guestbook-app
    spec:
      ports:
        - port: 6379
          targetPort: 6379
      selector:
        name: redis
        app: demo-guestbook-app
