apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: demo-guestbook-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: redis-service
      app: demo-guestbook-app
  template:
    metadata:
        name: redis
        labels:
            name: redis
            app: demo-guestbook-app
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
